# Generated by Django 5.2.3 on 2026-03-10 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('REGISTER_VERIFY', 'Register Verify'), ('PASSWORD_RESET', 'Password Reset')], default='REGISTER_VERIFY', max_length=30),
        ),
        migrations.CreateModel(
            name='OfflineAttendanceSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_event_id', models.CharField(max_length=120)),
                ('action', models.CharField(max_length=10)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_sync_logs', to='attendence.attendance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'local_event_id'], name='attendence__user_id_ce7c26_idx')],
                'unique_together': {('user', 'local_event_id')},
            },
        ),
    ]
