# Generated by Django 5.2.3 on 2026-03-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_alter_emailotp_purpose_offlineattendancesynclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_work_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
